[package]
name = "harbour"
version = "0.1.0"
authors = ["Alexandru Radovici <msg4alex@gmail.com>"]
edition = "2018"

[dependencies]
snailquote = "0.2.0"
chrono = "0.4"
users = "0.9"
tabular = "0.1.2"
structopt = "0.3"
